### ISSUE TITLE
HMI client doesn't continue after timeout

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/hmi#13]
After https://github.com/tue-robotics/hmi/blob/master/hmi/src/hmi/client.py#L80 it doesn't continue. Unless you wrap a try/except around https://github.com/tue-robotics/hmi/blob/master/hmi/src/hmi/client.py#L103.

Although this creates the problem that answer is not initialized. Which causes problem on https://github.com/tue-robotics/hmi/blob/master/hmi/src/hmi/client.py#L107/https://github.com/tue-robotics/hmi/blob/master/hmi/src/hmi/client.py#L107. Even when creating an empty QueryResult. Because json will not return anything from empty semantics.

Easy to test by reducing the waiting time of joke.py and disable the random_answerer.

**Comment by Rayman** [comment]
The `TimeoutException` is part of the design of the API, so it's not a bug

**Comment by MatthijsBurgh** [comment]
But what should happen after this ```TimeoutException``` is raised? Because when asking for another joke, when no answer is provided, the lights stay. Which means line https://github.com/tue-robotics/tue_robocup/blob/master/robot_skills/src/robot_skills/api.py#L40 is never reached. Which shouldn't be the case in my opinion.

**Comment by Rayman** [comment]
You're right, but the issue is thus in the `robot_skills/hmi`. It should try except, and then reraise
