### ISSUE TITLE
Actions

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/hmi#3]
## Mandatory
- [x] dragonfly ros server that inherits from hmi.server
- [x] two way communication from hmi server to windows dragonfly
- [x] `robot.hmi.query(description, spec, choices): {name: value}`
- [x] `robot.hmi.query_raw(description, spec): string`
- [x] mock of robot.ears.hear
- [ ] deprecation warning
- [ ] update all SMACH states (hear, hearOptions, hearOptionsExtra?)
- [ ] also let `speak` forward its sentence to the hmi description
- [x] add to the install dependencies
- [ ] test with big specs (egpsr)

## Nice to have
- [ ] hmi multicast server
- [ ] HTML5 GUI hmi.server
- [x] QR code hmi.server for the GPSR

## Bugs
- [ ] specs are not unloaded
- [ ] cancelling does not work
- [ ] say 'continue' has a timeout

@Rayman

**Comment by LoyVanBeek** [comment]
Also extend the Say-state to display the sentence in the HMI.

**Comment by Rayman** [comment]
To test this:
- `amigo_bringup`
  - modify `parameters/interaction/speech_client.yaml` to my laptop
- `dragonfly_speech_recognition` on branch 'hmi'
- `robot_launch_files` on branch 'hmi'
- `robot_skills` on branch 'hmi'

**Comment by Rayman** [comment]
Merged
