### ISSUE TITLE
New HMI API

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/hmi#4]
- [x] update `hmi_msgs` @reinzor 
- [x] update `grammar_parser`
  - [x] tests @reinzor 
- [x] update `dragonfly_speech_recognition`
  - [x] hmi_server_dragonfly_client @reinzor 
  - [x] `dragonfly_client` @reinzor 
  - [x] `dragonfly_server` @reinzor 
- [x] update `hmi_server` for the new message @rayman
- [x] update `robot_skills` @rayman

**Comment by reinzor** [comment]
Merged into master
